export { default as baithakBanner } from './baithak_banner_image.png';
export {default as bookLaunchBanner} from './book_launch_image.png';
export { default as creativeSpacesBanner } from './creative_spaces_banner_image.jpg';
export { default as eventVenturesBanner } from './event_venues_banner_image.jpg';
export { default as exhibitionBanner } from './exhibition_banner_image.jpg';
export { default as livingRoomBanner } from './living_room_banner_image.svg';
export { default as photographyBanner } from './photography_banner_image.jpg';
export { default as podcastBanner } from './podcast_banner_image.png';
export { default as wellnessBanner } from './wellness_banner_image.webp';
export { default as workshopsBanner } from './workshop_banner_image.jpg';
export { default as easyDiscovery } from './icons/easy_discovery.svg';
export { default as noAIPics } from './icons/no_ai_images.svg';
export { default as flexibleBooking } from './icons/flexible_booking_options.svg';
export { default as verifiedStudios } from './icons/verified_studios.svg';
export { default as cycloramaBanner } from './cyclorama_banner_image.png';
// new banners
export { default as soundHealingBanner } from './sound_healing.png';
export { default as danceRehearsalBanner } from './dance_rehearsal.png';
export { default as yogaBanner } from './yoga.png';
export { default as kitchenBanner } from './kitchen.png';
export { default as livingRoomNewBanner } from './living_room.png';
export { default as performanceBanner } from './performance.jpg';
export { default as theatreBanner } from './theatre.png';
export { default as supperClubBanner } from './supper_club.png';
export { default as outdoorSpaceBanner } from './outdoor_space.jpg';
export { default as bhajanClubbingBanner } from './bhajan_clubbing.png';
export { default as screeningSpaceBanner } from './screening _space.jpg';
export { default as artGalleryBanner } from './art_gallery.jpg';
export { default as warehouseStudioBanner } from './warehouse_studio.jpg';
export { default as brandPopUpBanner } from './brand_pop_up.png';